"""
Application constants.

This module contains all magic numbers and constant values used throughout
the application, organized by category for better maintainability.
"""

# Network and HTTP Constants
HTTP_STATUS_OK = 200
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_TOO_MANY_REQUESTS = 429
HTTP_STATUS_PAYMENT_REQUIRED = 402
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500

DEFAULT_APP_PORT = 8000
HTTPS_PORT = 443

# Timeout and Retry Constants
HTTP_TIMEOUT_SECONDS = 30.0
MOCK_FACILITATOR_TIMEOUT_SECONDS = 10.0
X402_RETRY_DELAY_MS = 1000
X402_RETRY_DELAY_SECONDS = 1.0
X402_MAX_RETRIES = 3

# Database Constants
DB_POOL_RECYCLE_SECONDS = 300
DB_POOL_SIZE = 10
DB_MAX_OVERFLOW = 20

# Rate Limiting Constants
DEFAULT_RATE_LIMIT_REQUESTS_PER_MINUTE = 100
MCP_RATE_LIMIT_DELAY_SECONDS = 0.1

# Pagination Constants
DEFAULT_PAGE_LIMIT = 20
MAX_PAGE_LIMIT = 100
MIN_PAGE_LIMIT = 1
DEFAULT_MARKETS_LIMIT = 50

# Agent Constants
AGENT_MAX_ITERATIONS = 50
AGENT_TIMEOUT_SECONDS = 300
AGENT_DEFAULT_BUDGET_USD = 100.0
HITL_APPROVAL_THRESHOLD_USD = 10.0
JWT_EXPIRATION_HOURS = 24

# Financial Constants
DEFAULT_DAILY_LIMIT_USD = 1000.0
DEFAULT_SLIPPAGE_TOLERANCE_PERCENT = 1.0

# Cache Constants
DEFAULT_CACHE_TTL_SECONDS = 300
METRICS_MAX_HISTORY = 10000

# Validation Constants
MAX_COMMAND_LENGTH = 10000
MAX_REASON_LENGTH = 500